[build]
rustc-wrapper = "/usr/bin/sccache"

[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[source.crates-io]
replace-with = "ustc"

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"
